apiVersion: v1
kind: Namespace
metadata:
  name: $ENV
  labels:
    name: $ENV
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: $ENV
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: monicashinde3/nodjs-rest-containerized-ci-cd
        ports:
        - containerPort: 3000
      
---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: $ENV
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
    protocol: TCP
  selector:
    app: nodejs